config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/mini' => 'pages#minimal', as: :mini
  root to: redirect('/mini', status: 302)

  get '/reading' => 'pages#reading', as: :reading
  get '/hidden' => 'pages#hidden', as: :hidden
  get '/soonest' => 'pages#soonest', as: :soonest
  get '/filter' => 'pages#filter', as: :filter
  post '/find' => 'pages#find', as: :find

  resources :pages
  resources :tags
  resources :htmls, only: ['edit']
  resources :notes, only: %w[edit show]
  resources :my_notes, only: ['edit']
  resources :end_notes, only: ['edit']
  resources :parts, only: %w[new edit create]
  resources :rates, only: %w[show create edit]
  resources :refetches, only: %w[show create]
  resources :scrubs, only: ['show']
  resources :splits, only: %w[show create]
  Tag.types.each do |type|
    resources type.pluralize.downcase.to_sym, only: %w[index show]
  end

  get '/downloads/:id.:format' => 'downloads#show', :as => 'download'
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  def show
    @page = Page.find(params[:id])
  end

  def edit
    @page = Page.find(params[:id])
  end
end

app/views/notes/edit.html.haml
.notes
  = form_for @page do |f|
    = f.submit "Update"
    = f.text_area :notes, :rows => 10, :cols => 33

app/views/notes/show.html.haml
.title
  Notes for
  =link_to @page.title, page_path(@page)
.meta
  = link_to "Edit Notes", edit_note_path(@page)
  = link_to "Scrub Notes", scrub_path(@page, notes: true)
.notes
  =raw @page.formatted_notes