config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/mini' => 'pages#minimal', as: :mini
  root to: redirect('/mini', status: 302)

  get '/reading' => 'pages#reading', as: :reading
  get '/hidden' => 'pages#hidden', as: :hidden
  get '/soonest' => 'pages#soonest', as: :soonest
  get '/filter' => 'pages#filter', as: :filter
  post '/find' => 'pages#find', as: :find

  resources :pages
  resources :tags
  resources :htmls, only: ['edit']
  resources :notes, only: %w[edit show]
  resources :my_notes, only: ['edit']
  resources :end_notes, only: ['edit']
  resources :parts, only: %w[new edit create]
  resources :rates, only: %w[show create edit]
  resources :refetches, only: %w[show create]
  resources :scrubs, only: ['show']
  resources :splits, only: %w[show create]
  Tag.types.each do |type|
    resources type.pluralize.downcase.to_sym, only: %w[index show]
  end

  get '/downloads/:id.:format' => 'downloads#show', :as => 'download'
end

app/controllers/downloads_controller.rb
# frozen_string_literal: true

class DownloadsController < ApplicationController
  def show
    page = Page.find(params[:id])

    respond_to do |format|
      # html for reading inline
      format.html do
        page.render_html
        send_file(page.temporary_file('.html'), type: 'text/html', disposition: 'inline')
      end
      # html for reading aloud inline for audiobooks
      format.read do
        page.render_read_aloud
        send_file(page.temporary_file('.read'), type: 'text/html', disposition: 'inline')
      end
      # epub for downloading to read offline
      format.epub do
        page.render_epub
        page.set_reading unless page.hidden?
        send_file(page.temporary_file('.epub'), type: 'application/epub')
      end
    end
  end
end

app/views/downloads/_end_notes.html.haml
-if page.at_end && page.end_notes.present?
  %b Page Endnotes:
  .end_notes=simple_format page.end_notes

.links
  %p{class: "rate_#{page.title.sum}"}
    = page.read? ? "ReRate" : "Rate"
    #{page.type}:
    =link_to page.title, @url + rate_path(page)

  -if (defined?(last) && page.ao3? && page.not_ao3_series?) || page.ao3_work?
    %p.kudos
      Leave Kudos or Comments on:
      -if page.can_have_parts? && page.parts.last.url
        =link_to page.title, page.parts.last.url + "#comments"
      -else
        =link_to page.title, page.url + "#comments"

  -if defined?(last) && page.next_part
    %p.next
      Next:
      =link_to page.next_part.title, @url + download_url_for_page(page.next_part, ".html")

app/views/downloads/_h2.html.haml
%h2{:style=> "page-break-before:always", :class => "chapter", :id => child.header_id}=link_to child.download_part_title, @url + page_path(child)
=render :partial => "downloads/notes", :locals => {:page => child} if child.show_notes

- if child.parts.empty?
  .content=raw child.epub_html
- else
  - child.not_hidden_parts.each do |grandchild|
    =render :partial => "downloads/h3", :locals => {:grandchild => grandchild}

=render :partial => "downloads/end_notes", :locals => {page: child}

app/views/downloads/_h3.html.haml
%h3{:style=> "page-break-before:always", :class => "chapter", :id => grandchild.header_id}=link_to grandchild.download_part_title, @url + page_path(grandchild)
=render :partial => "downloads/notes", :locals => {:page => grandchild} if grandchild.show_notes

- if grandchild.parts.empty?
  .content=raw grandchild.epub_html
- else
  - grandchild.not_hidden_parts.each do |ggchild|
    =render :partial => "downloads/h4", :locals => {:ggchild => ggchild}

=render :partial => "downloads/end_notes", :locals => {page: grandchild}

app/views/downloads/_h4.html.haml
%h4{:style=> "page-break-before:always", :class => "chapter", :id => ggchild.header_id}=link_to ggchild.download_part_title, @url + page_path(ggchild)
=render :partial => "downloads/notes", :locals => {:page => ggchild} if ggchild.show_notes
.content=raw ggchild.epub_html
=render :partial => "downloads/end_notes", :locals => {page: ggchild}

app/views/downloads/_notes.html.haml
.notes{:style=> "page-break-after:always"}
  %b #{page.class} Notes:
  =simple_format page.notes
  -if page.hr1?
    %hr
  =simple_format page.my_notes
  -if page.hr2?
    %hr
  =simple_format page.end_notes unless page.at_end
  %hr

app/views/downloads/read.html.haml
.tags=@page.download_tag_string
.my_notes=raw @page.formatted_my_notes
.notes=raw @page.formatted_notes

#page=raw @page.read_html

.end_notes=raw @page.formatted_end_notes

.form
  = form_for @page do
    = submit_tag "Audiobook created"

app/views/downloads/show.html.haml
%h1{:style=> "page-break-before:always", :class => "chapter", :id => @page.header_id}=link_to @page.title, @url + page_path(@page)
=[@page.wip_string, @page.favorite_string].without("").join(", ")
=render :partial => "downloads/notes", :locals => {:page => @page.parent} if @page.parent && @page.parent.show_notes
=render :partial => "downloads/notes", :locals => {:page => @page} if @page.show_notes

- if @page.can_have_parts?
  - @page.not_hidden_parts.each do |child|
    =render :partial => "downloads/h2", :locals => {:child => child}
- else
  .content=raw @page.epub_html


=render :partial => "downloads/end_notes", :locals => {:page => @page, :last => true}